#define RX_ANTENNA 0
#define TX_ANTENNA 1
#define ALL_ANTENNAS 2

// COMMAND ENUMERATORS
enum cmdenum: byte {
  STOP_ENUM,
  ROTATE_RX_ANTENNA_CW_ENUM,
  ROTATE_RX_ANTENNA_CCW_ENUM,
  ROTATE_TX_ANTENNA_CW_ENUM,
  ROTATE_TX_ANTENNA_CCW_ENUM,
  ROTATE_RX_ANTENNA_TO_ENUM,
  ROTATE_TX_ANTENNA_TO_ENUM,
  SET_TARGET_GRID_ENUM,
  SYNC_TX_2_RX_ENABLE_ENUM,
  SYNC_TX_2_RX_DISABLE_ENUM,
  LINK_TX_AND_RX_ENABLE_ENUM,
  LINK_TX_AND_RX_DISABLE_ENUM,
  PTT_AUTOMATION_ENABLED_ENUM,
  PTT_AUTOMATION_DISABLED_ENUM
} COMMAND_ENUM;

// ANTENNA ROTATION SYNC
enum rlnk: bool {
  ROTATE_ONE,
  ROTATE_BOTH
} ROTATE_WHAT;

// READ THE RTC CLOCK NOW
enum rrc: byte {
  TIMED_RTC_READ,
  READ_RTC_NOW
} READ_RTC_CLOCK;

// RX ROTATION STATUS ENUMERATORS *** REMOVE DEFINITIONS IF NOT NEEDED ***
enum rxrs: byte {
  RX_IDLE,
  RX_SLOW_START_CW, 
  RX_SLOW_START_CCW,
  RX_NORMAL_CW,
  RX_NORMAL_CCW,
  RX_TO_TARGET_CW,
  RX_TO_TARGET_CCW,
  RX_SLOW_DOWN_CW,
  RX_SLOW_DOWN_CCW,
  RX_INITIALIZE_SLOW_START_CW,
  RX_INITIALIZE_SLOW_START_CCW,
  RX_INITIALIZE_TIMED_SLOW_DOWN_CW,
  RX_INITIALIZE_TIMED_SLOW_DOWN_CCW,
  RX_TIMED_SLOW_DOWN_CW,
  RX_TIMED_SLOW_DOWN_CCW,
  RX_INITIALIZE_DIR_CHANGE_TO_CW,
  RX_INITIALIZE_DIR_CHANGE_TO_CCW,
  RX_INITIALIZE_NORMAL_CW,
  RX_INITIALIZE_NORMAL_CCW
} RX_ROTATION_STATUS = RX_IDLE;

// TX ROTATION STATUS ENUMERATORS *** REMOVE DEFINITIONS IF NOT NEEDED ***
enum txrs: byte {
  TX_IDLE,
  TX_SLOW_START_CW,
  TX_SLOW_START_CCW,
  TX_NORMAL_CW,
  TX_NORMAL_CCW,
  TX_TO_TARGET_CW,
  TX_TO_TARGET_CCW,
  TX_SYNC_TO_RX_CW,
  TX_SYNC_TO_RX_CCW,
  TX_SLOW_DOWN_CW,
  TX_SLOW_DOWN_CCW,
  TX_INITIALIZE_SLOW_START_CW,
  TX_INITIALIZE_SLOW_START_CCW,
  TX_INITIALIZE_TIMED_SLOW_DOWN_CW,
  TX_INITIALIZE_TIMED_SLOW_DOWN_CCW,
  TX_TIMED_SLOW_DOWN_CW,
  TX_TIMED_SLOW_DOWN_CCW,
  TX_INITIALIZE_DIR_CHANGE_TO_CW,
  TX_INITIALIZE_DIR_CHANGE_TO_CCW,
  TX_INITIALIZE_NORMAL_CW,
  TX_INITIALIZE_NORMAL_CCW,
} TX_ROTATION_STATUS = TX_IDLE;

// ROTATIONS STATUS ENUMERATORS TEXT
char ROTATION_STATUS_TEXT[][15] = {
  "              ",
  "SLOWSTART CW",
  "SLOWSTART CCW",
  "MOVING CW",
  "MOVING CCW",
  "TARGETING CW",
  "TARGETING CCW",
  "SYNCING TX CW",
  "SYNCING TX CCW",
};

byte running_status = {B00000000};
// PTT ACTIVE
// RX LINKED TO TX
// 1 or 2 ANTENNAS
// TX 2 RX (ACTIVATED/STOPPED)

//theDisplay[3] |= (1 << bitnumber); // for setting the bit
//theDisplay[3] &= ~(1 << bitnumber); // for clearing the bit
//theDisplay[3] ^= (1 << bitnumber); // togling
// bitSet(x, n)
//
// Parameters
// x: the numeric variable whose bit to set.
// n: which bit to set, starting at 0 for the least-significant (rightmost) bit.
