#define RX_ANTENNA 0
#define TX_ANTENNA 1
#define ALL_ANTENNAS 2

// COMMAND ENUMERATORS
enum cmdenum: byte {
  NO_COMMAND,
  STOP,
  ROTATE_RX_ANTENNA_CW,
  ROTATE_RX_ANTENNA_CCW,
  ROTATE_TX_ANTENNA_CW,
  ROTATE_TX_ANTENNA_CCW,
  ROTATE_RX_ANTENNA_TO,
  ROTATE_TX_ANTENNA_TO,
  SET_TARGET_GRID,
  SYNC_TX_2_RX_ENABLE,
  SYNC_TX_2_RX_DISABLE,
  LINK_TX_AND_RX_ENABLE,
  LINK_TX_AND_RX_DISABLE,
  PTT_AUTOMATION_ENABLED,
  PTT_AUTOMATION_DISABLED,
  CALIBRATE_RX_ANTENNA_CW,
  CALIBRATE_RX_ANTENNA_CCW,
  CALIBRATE_TX_ANTENNA_CW,
  CALIBRATE_TX_ANTENNA_CCW,
  SAVE_CALLSIGN_TO_EEPROM,
  SAVE_GRID_TO_EEPROM,
  SEND_CONFIG,
  OTHER
} COMMAND;

// ANTENNA ROTATION SYNC
enum rlnk: bool {
  ROTATE_ONE,
  ROTATE_BOTH
} ROTATE_WHAT;

// ROTATIONS STATUS 
enum rx_rdir: int {
  RX_NO_ROTATING,
  RX_ROTATING_CW,
  RX_ROTATING_CCW
} RX_ROTATING;

enum tx_rdir: int {
  TX_NO_ROTATING,
  TX_ROTATING_CW,
  TX_ROTATING_CCW
} TX_ROTATING;

enum rdir: bool {
  CW,
  CCW
} ROTATION_WAY;

// TIMING CONTROL FOR SOME FUNCTIONS
enum rrc: byte {
  TIMED,
  NOW
};

// RX ROTATION STATUS ENUMERATORS *** REMOVE DEFINITIONS IF NOT NEEDED ***
enum rxrs: byte {
  RX_IDLE,
  RX_SLOW_START_CW, 
  RX_SLOW_START_CCW,
  RX_NORMAL_CW,
  RX_NORMAL_CCW,
  RX_TO_TARGET_CW,
  RX_TO_TARGET_CCW,
  RX_SYNC_TO_TX_CW,
  RX_SYNC_TO_TX_CCW,
  RX_SLOW_DOWN_CW,
  RX_SLOW_DOWN_CCW,
  RX_SYNC_TO_TX_PTT_CW,
  RX_SYNC_TO_TX_PTT_CCW,
  RX_INITIALIZE_SLOW_START_CW,
  RX_INITIALIZE_SLOW_START_CCW,
  RX_INITIALIZE_TIMED_SLOW_DOWN_CW,
  RX_INITIALIZE_TIMED_SLOW_DOWN_CCW,
  RX_TIMED_SLOW_DOWN_CW,
  RX_TIMED_SLOW_DOWN_CCW,
  RX_INITIALIZE_DIR_CHANGE_TO_CW,
  RX_INITIALIZE_DIR_CHANGE_TO_CCW,
  RX_INITIALIZE_NORMAL_CW,
  RX_INITIALIZE_NORMAL_CCW
} RX_ROTATION_STATUS = RX_IDLE;

// TX ROTATION STATUS ENUMERATORS *** REMOVE DEFINITIONS IF NOT NEEDED ***
enum txrs: byte {
  TX_IDLE,
  TX_SLOW_START_CW,
  TX_SLOW_START_CCW,
  TX_NORMAL_CW,
  TX_NORMAL_CCW,
  TX_TO_TARGET_CW,
  TX_TO_TARGET_CCW,
  TX_SYNC_TO_RX_CW,
  TX_SYNC_TO_RX_CCW,
  TX_SLOW_DOWN_CW,
  TX_SLOW_DOWN_CCW,
  TX_SYNC_TO_RX_PTT_CW,
  TX_SYNC_TO_RX_PTT_CCW,
  TX_INITIALIZE_SLOW_START_CW,
  TX_INITIALIZE_SLOW_START_CCW,
  TX_INITIALIZE_TIMED_SLOW_DOWN_CW,
  TX_INITIALIZE_TIMED_SLOW_DOWN_CCW,
  TX_TIMED_SLOW_DOWN_CW,
  TX_TIMED_SLOW_DOWN_CCW,
  TX_INITIALIZE_DIR_CHANGE_TO_CW,
  TX_INITIALIZE_DIR_CHANGE_TO_CCW,
  TX_INITIALIZE_NORMAL_CW,
  TX_INITIALIZE_NORMAL_CCW,
} TX_ROTATION_STATUS = TX_IDLE;

// ROTATIONS STATUS ENUMERATORS TEXT - NO MORE THAN 14 CHARACTERS!
char ROTATION_STATUS_TEXT[][15] = {
//"12345678901234"
  "              ", // IDLING, NO MESSAGE 
  "SLOWSTART CW",
  "SLOWSTART CCW",
  "MOVING CW",
  "MOVING CCW",
  "TARGETING CW",
  "TARGETING CCW",
  "SYNCING TX CW",
  "SYNCING TX CCW",
  "SLOWSTOP CW",
  "SLOWSTOP CCW",
  "FOLLOWING CW",
  "FOLLOWING CCW"
};


