// COMMAND ENUMERATORS
const byte ROTATE_RX_ANTENNA_CW_ENU  = 1;
const byte ROTATE_RX_ANTENNA_CCW_ENU = 2;
const byte ROTATE_TX_ANTENNA_CW_ENU  = 3;
const byte ROTATE_TX_ANTENNA_CCW_ENU = 4;

// READ THE RTC CLOCK NOW
const bool READ_RTC_NOW = 1;

// RX ROTATION STATUS ENUMERATORS
#define RX_IDLE 0
#define RX_SLOW_START_CW 1
#define RX_SLOW_START_CCW 2
#define RX_NORMAL_CW 3
#define RX_NORMAL_CCW 4
#define RX_SLOW_DOWN_CW 5
#define RX_SLOW_DOWN_CCW 6
#define RX_INITIALIZE_SLOW_START_CW 7
#define RX_INITIALIZE_SLOW_START_CCW 8
#define RX_INITIALIZE_TIMED_SLOW_DOWN_CW 9
#define RX_INITIALIZE_TIMED_SLOW_DOWN_CCW 10
#define RX_TIMED_SLOW_DOWN_CW 11
#define RX_TIMED_SLOW_DOWN_CCW 12
#define RX_INITIALIZE_DIR_CHANGE_TO_CW 13
#define RX_INITIALIZE_DIR_CHANGE_TO_CCW 14
#define RX_INITIALIZE_NORMAL_CW 15
#define RX_INITIALIZE_NORMAL_CCW 16

// TX ROTATION STATUS ENUMERATORS
#define TX_IDLE 0
#define TX_SLOW_START_CW 1
#define TX_SLOW_START_CCW 2
#define TX_NORMAL_CW 3
#define TX_NORMAL_CCW 4
#define TX_SLOW_DOWN_CW 5
#define TX_SLOW_DOWN_CCW 6
#define TX_INITIALIZE_SLOW_START_CW 7
#define TX_INITIALIZE_SLOW_START_CCW 8
#define TX_INITIALIZE_TIMED_SLOW_DOWN_CW 9
#define TX_INITIALIZE_TIMED_SLOW_DOWN_CCW 10
#define TX_TIMED_SLOW_DOWN_CW 11
#define TX_TIMED_SLOW_DOWN_CCW 12
#define TX_INITIALIZE_DIR_CHANGE_TO_CW 13
#define TX_INITIALIZE_DIR_CHANGE_TO_CCW 14
#define TX_INITIALIZE_NORMAL_CW 15
#define TX_INITIALIZE_NORMAL_CCW 16